version: '3.8' 
services:
  db: 
    image: mysql:8.0
    container_name: demo_db 
    #ports:
      #3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}       
      # MYSQL_USER: ${MYSQL_USER}              
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}         
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 

  demo: 
    build: . 
    container_name: demo-container 
    ports:
      - "80:8000" 
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on: 
      db:
        condition: service_healthy 
    volumes:
      - .:/app 
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes: 
  db_data: 
